# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -a
    silent: true
    
  release:
    desc: build release-art
    cmds:
    - mkdir -p release/
    - cp -r devpod release/devpod

  build:
    desc: build release-art
    cmds:
    - task post-build-stamp
    - chmod +x src/devpod/*.sh
    - chmod +x src/devpod/*.yml
        
  post-build-stamp:
    desc: _
    vars:
      base_file_url: https://raw.githubusercontent.com/yairdar/devpod/main/src/devpod
      items:
        sh: ls -1 src/devpod
    cmds:
    - |-
      cat << FQD > init.sh
      #!/usr/bin/env sh
      set -e
      mkdir -p devpod && cd devpod      
      BASE_FILE_URL={{.base_file_url}}
      xargs -P 4 -I{} wget \$BASE_FILE_URL/{} -O {} << FHJ
      {{.items}}
      FHJ
      FQD
  
  init-from-gitub-latest:
    desc: API snippen of init with devpod applied on self
    cmds:
    - cmd: |-
        curl -L https://raw.githubusercontent.com/yairdar/devpod/main/init.sh \
        | bash
        
  update-context:
    desc: API snippen of init with devpod applied on self
    cmds:
    - cmd: bash devpod/update-context.sh