# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
    
  build:
    desc: build release-art
    cmds:
    - mkdir -p release/
    - cp -r devpod release/devpod
