# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -a
    silent: true
    
  release:
    desc: build release-art
    cmds:
    - mkdir -p release/
    - cp -r devpod release/devpod

  build:
    desc: build release-art
    cmds:
    - task post-build-stamp
    - chmod +x src/devpod/*.sh
    - chmod +x src/devpod/*.yml

  test:
    desc: run tests
    cmds:
    - task -d tests run-tests -o prefixed
        
  post-build-stamp:
    desc: _
    vars:
      base_file_url: https://raw.githubusercontent.com/yairdar/devpod/main/src/devpod
      items:
        sh: ls -1 src/devpod
    cmds:
    - |-
      cat << MRK_CAT > init.sh
      #!/usr/bin/env sh
      set -e
      DEVPOD_INIT_DIR=\${DEVPOD_INIT_DIR:-devpod}
      mkdir -p \$DEVPOD_INIT_DIR && cd \$DEVPOD_INIT_DIR      
      
      BASE_FILE_URL={{.base_file_url}}
      xargs -P 4 -I{} wget \$BASE_FILE_URL/{} -O {} << MRK_XRGS
      {{.items}}
      MRK_XRGS

      chmod +x *.*
      echo 'made file executables'
      MRK_CAT
  
  init-from-gitub-latest:
    desc: API snippen of init with devpod applied on self
    cmds:
    - cmd: |-
        curl -L https://raw.githubusercontent.com/yairdar/devpod/main/init.sh \
        | bash
        
  update-context:
    desc: API snippen of init with devpod applied on self
    cmds:
    - cmd: bash devpod/update-context.sh

  open-repo-web:
    desc: open on web repo view
    cmds:
    - open https://github.com/yairdar/devpod