FROM ubuntu:20.04
# what's the variable on the next line and what is it for?
ENV IN_DOCKER 1

# install wget to be able to fetch init.sh
RUN apt update && apt install -y wget

# install python3 to test install-task-completion in setup.zsh.tools.yml
RUN apt update && apt install -y python3

# run Quick Install on src folder
RUN echo "Test after merge with main branch. Running Quick Install on src folder"
RUN echo "Inititalize $(pwd) with devpod"
RUN echo "This will create directory `devpod`, run this from your repo root so `devpod` became 1 level dir."
RUN wget -q -O - https://github.com/yairdar/devpod/blob/main/tests/test-after-merge/init.sh | bash

RUN echo "run setup idempotent process, only missing tools will be installed"
RUN bash devpod/install-deps.sh install-all
